### ISSUE TITLE
Fails if using an image folder other than "/"

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_Slideshow#7]
Currently the library fails if you change the image folder to anything but "/".

```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 7, in <module>
  File "adafruit_slideshow.py", line 195, in __init__
  File "adafruit_slideshow.py", line 294, in advance
OSError: [Errno 2] No such file/directory
```

**Comment by ladyada** [comment]
use

[folder+"/"+f for f in os.listdir(folder) if (f.endswith(".bmp") and not f.startswith("."))]
